name: stealth-ops-game # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Stealth Ops Mission
summary: Infiltrate enemy bases in secret missions.
description: A tactical espionage game where you avoid detection, disable security, and complete high-stakes objectives. Perfect for stealth lovers and strategy fans.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  stealth-ops-game:
    command: bin/stealth-ops-game-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  stealth-ops-game:
    plugin: dump
    source: .
    organize:
      stealth-ops-game-bin: bin/
